services:
  - type: web
    name: pronske-guitars
    repo: https://github.com/jackpronske/Pronske-Guitars
    branch: main
    runtime: node
    plan: free
    buildCommand: NODE_ENV=development npm ci && npm run build-prod
    startCommand: node server
